name: summer_olymics_visualizations
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.13
  - jupyter=1.0.0
  - pandas=1.4.1
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - openpyxl=3.0.9
  - plotly=5.6.0
  - pip=21.2.4
  - dash=2.3.1
  - dash-bootstrap-components=1.1.0
  - scikit-image=0.19.2