name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: summer_olymics_visualizations
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build
        shell: bash -l {0}
        run: |
          conda info
          conda list
          cd dashboard
          make clean
          make build

      - name: Deploy
        shell: bash -l {0}
        run: |
          cd dashboard/127.0.0.1:8050
          touch .nojekyll
          git config --global init.defaultBranch gh-pages
          git config --global user.name ${{ secrets.GH_USER }}
          git config --global user.email "${{ secrets.GH_MAIL }}"
          git init
          git add *
          git add .nojekyll
          git commit -m "update"
          git remote add gh-token "https://${{ secrets.GH_TOKEN}}@github.com/rdarbinyan/summer_olymics_visualizations.git"
          git push -f gh-token gh-pages